# Generated by Django 4.2.2 on 2023-07-29 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                (
                    "picture",
                    models.ImageField(
                        blank=True, null=True, upload_to="item_pictures/"
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
